
name: $(BuildDefinitionName)_$(VersionNumber)_$(SourceBranchName)
trigger:
- main
parameters:
- name: logging
  default: All
  type: string

variables:
- name: artifactsPath
  value: "$(Build.ArtifactStagingDirectory)/artifacts"
- name: BaseVersionNumber 
  value: "0.1"  
- name: Minor 
  value: $[counter(variables['BaseVersionNumber'], 1)]
- name: VersionNumber 
  value: $(BaseVersionNumber).$(Minor)
- name: verboselogging
  value: ${{parameters.logging}}
pool:
  vmImage: 'windows-latest'
stages:
- stage: build
  displayName: Build 
  jobs:
  - job: Build
    displayName: Build jobs 
    steps:
    - checkout: self
      clean: false 

    - powershell: |
       &"$(System.DefaultWorkingDirectory)/.build/pipeline-tasks.ps1" -Install   
      displayName: 'Install tools'

    - powershell: |
        &"$(System.DefaultWorkingDirectory)/.build/pipeline-tasks.ps1" -Build  -Install  
      displayName: 'Build'

    - powershell: |
        &"$(System.DefaultWorkingDirectory)/.build/pipeline-tasks.ps1" -Package -Install
      displayName: 'Package'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifacts Sql.System.Dacpacs'
      inputs:
        PathtoPublish: '$(artifactsPath)/Sql.System.Dacpacs'
        ArtifactName: 'Sql.System.Dacpacs'
      condition: succeededOrFailed()
